apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitm-proxy
  labels:
    app: mitm-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mitm-proxy
  template:
    metadata:
      labels:
        app: mitm-proxy
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: mitm-proxy
        image: asifdroid63/mitm-proxy:latest
        ports:
        - containerPort: 5001
---
# This service will REPLACE the original flask-app-2 service during the attack
apiVersion: v1
kind: Service
metadata:
  name: mitm-flask-app-2  # Different name initially
  labels:
    app: mitm-proxy
spec:
  selector:
    app: mitm-proxy
  ports:
  - port: 5001
    targetPort: 5001
